[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn dashboard_thopen:app --chdir thopen --bind 0.0.0.0:$PORT --workers 2 --timeout 180"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
